language: python
branches:
  only:
    - wpt-downstream
python:
  - "2.7"
# command to install dependencies
install: "cd wpt-sync; source travis-install.sh"
# command to run tests
script: pytest test/
