sudo: required

language: python
branches:
  only:
    - wpt-downstream
python:
  - "2.7"

services:
  - docker

install:
  - docker build -t wptsync_dev --file wpt-sync/docker/dev/Dockerfile .

script:
  - docker run -it --entrypoint "/app/venv/bin/pytest" wptsync_dev
