sudo: required

language: python
branches:
  only:
    - wpt-downstream
python:
  - "2.7"

# Upgrade to newer docker version
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

install:
  - docker build -t wptsync_dev --file wpt-sync/docker/dev/Dockerfile .

script:
  - docker run -it --mount type=bind,source=$(pwd),target=/app/vct --entrypoint "/app/venv/bin/pytest" wptsync_dev
