sudo: required

language: python
branches:
  only:
    - wpt_no_db
python:
  - "2.7"

# Upgrade to newer docker version
addons:
  apt:
    packages:
      - docker-ce

services:
  - docker

install:
  - docker build -t wptsync_dev --file wpt-sync/docker/dev/Dockerfile .
  - sudo chown -R 10001 ./wpt-sync

script:
  - docker run -it --env WPTSYNC_REPO_ROOT=/app/vct/wpt-sync/test/testdata --mount type=bind,source=$(pwd),target=/app/vct --entrypoint "/app/venv/bin/pytest" wptsync_dev

notifications:
  irc:
    channels:
      - "irc.mozilla.org#wpt-sync"
    on_success: change
    on_failure: always
