version: '3'
# This is kind of broken now, you probably don't want to use it.
services:
  sync:
    user: wptsync
    build:
      # root of version-control-tools repo
      context: ../../..
      dockerfile: wpt-sync/docker/dev/Dockerfile_compose
    volumes:
      - ../../..:/home/wptsync/vct
      - wptsync-workspace:/home/wptsync/workspace
      # this serves as a mozilla-unified remote in dev env
      - ${PATH_TO_GECKO_HG}:/home/wptsync/gecko-hg
    environment:
      - PYTHONPATH=/home/wptsync/vct/wpt-sync
      - WPTSYNC_ROOT=/home/wptsync/workspace
    command: /home/wptsync/venv/bin/wptsync listen
  rabbitmq:
      image: rabbitmq
      ports:
        - 5672:5672
  celery:
    user: wptsync
    build:
      # root of version-control-tools repo
      context: ../../..
      dockerfile: wpt-sync/docker/dev/Dockerfile_compose
    volumes:
      - ../../..:/home/wptsync/vct
      - wptsync-workspace:/home/wptsync/workspace
      # this serves as a mozilla-unified remote in dev env
      - ${PATH_TO_GECKO_HG}:/home/wptsync/gecko-hg
    command: /home/wptsync/start_celeryworker.sh
    environment:
      - PYTHONPATH=/home/wptsync/vct/wpt-sync
      - WPTSYNC_ROOT=/home/wptsync/workspace
    env_file:
      - ../celery_variables.env
    depends_on:
      - rabbitmq
  celerybeat:
    user: wptsync
    build:
      # root of version-control-tools repo
      context: ../../..
      dockerfile: wpt-sync/docker/dev/Dockerfile_compose
    volumes:
      - ../../..:/home/wptsync/vct
      - wptsync-workspace:/home/wptsync/workspace
      # this serves as a mozilla-unified remote in dev env
      - ${PATH_TO_GECKO_HG}:/home/wptsync/gecko-hg
    command: /home/wptsync/start_celerybeat.sh
    environment:
      - PYTHONPATH=/home/wptsync/vct/wpt-sync
      - WPTSYNC_ROOT=/home/wptsync/workspace
    env_file:
      - ../celery_variables.env
    depends_on:
      - rabbitmq
volumes:
  wptsync-workspace:
