# This playbook configures a system to perform syncing of web-platform-tests
#
# By default, tasks are executed as the wptsync user.
---
- name: create wptsync user
  user: name=wptsync
        shell=/bin/bash
        state=present

- name: create ~wptsync/.ssh
  file: path=/home/wptsync/.ssh
        state=directory
        owner=wptsync
        group=wptsync
        mode=0700

- name: install ssh known_hosts file
  copy: src=known_hosts
        dest=/home/wptsync/.ssh/known_hosts
        mode=0600
  become_user: wptsync

# - name: ssh config for wptsync user
#   template: src=wptsync-ssh_config.j2
#             dest=/home/wptsync/.ssh/config
#             mode=0600
#   become_user: wptsync
#
- name: git config for wptsync user
  template: src=wptsync-git_config.j2
            dest=/home/wptsync/.gitconfig
            mode=0600
  become_user: wptsync
#
# - name: install SSH keys
#   copy: dest=/home/wptsync/.ssh/id_{{ item.name }}
#         content="{{ item.value }}"
#         mode=0600
#   with_items:
#     - { name: github, value: "{{ servo_github_ssh_key }}" }
#     - { name: hgmo, value: "{{ servo_hgmo_ssh_key }}" }
#   become_user: wptsync
#
- name: create virtualenv
  include: ../../../tasks/virtualenv.yml
           venv={{ venv_path | mandatory }}
           requirements=../../wpt-sync/prod-requirements.txt
  become_user: wptsync

- name: copy wheels to server
  copy: src={{ vct | mandatory }}/venv/wheelhouse/{{ item }}
        dest=/home/wptsync/{{ item }}
        owner=wptsync
        group=wptsync
        mode=0644
  with_items:
    - "{{ wptsync_wheel | mandatory }}"
    - "{{ mozautomation_wheel | mandatory }}"
  become_user: wptsync

- name: install wheels into virtualenv
  command: /home/wptsync/venv/bin/pip install --upgrade --no-deps --force-reinstall /home/wptsync/{{ item }}
  with_items:
    - "{{ mozautomation_wheel | mandatory }}"
    - "{{ wptsync_wheel | mandatory }}"
  become_user: wptsync

- name: set up git-cinnabar
  include: git-cinnabar.yml
  become_user: wptsync

- name: create wptsync root directory (workspace)
  file: path={{ wptsync_root | mandatory }}
        state=directory
        owner=wptsync
        group=wptsync
        mode=0700

- name: install wptsync config files
  template: src={{ item }}.j2
            dest={{ wptsync_root | mandatory }}/{{ item }}
            mode=0644
  with_items:
    - sync.ini
    - credentials.ini
  become_user: wptsync

- name: configure repositories
  command: /home/wptsync/venv/bin/wptsync init
  become_user: wptsync

- name: seed web-platform-tests repository
  command: /home/wptsync/venv/bin/wptsync fetch web-platform-tests
  become_user: wptsync
  environment:
    PATH: "{{ venv_path | mandatory }}/bin:{{ ansible_env.PATH }}:{{ git_cinnabar_path | mandatory }}"
    WPTSYNC_ROOT: "{{ wptsync_root | mandatory }}"

- name: seed gecko repository
  command: /home/wptsync/venv/bin/wptsync fetch gecko
  become_user: wptsync
  async: 100000
  poll: 30
  environment:
    PATH: "{{ venv_path | mandatory }}/bin:{{ ansible_env.PATH }}:{{ git_cinnabar_path | mandatory }}"
    WPTSYNC_ROOT: "{{ wptsync_root | mandatory }}"

# start celery worker and pulse listener
# could use systemd, celeryd
