version: '3'
services:
  sync:
    user: app
    build:
      context: ..
      dockerfile: ./wpt-sync/docker/dev/Dockerfile
    volumes:
     - ..:/app/vct
     - ./logs:/app/workspace/logs
     - ./ssh:/app/ssh
     - ./repos:/app/repos
     - ./work:/app/workspace/work
     - ./credentials.ini:/app/workspace/credentials.ini
     - ./sync.ini:/app/workspace/sync.ini
    environment:
     - WPTSYNC_CREDS=/app/workspace/credentials.ini
    command: /app/start_wptsync.sh --worker
