version: '3'
services:
  sync:
    user: wptsync
    build: .
    volumes:
     - .:/home/wptsync/wpt-sync
    environment:
     - PYTHONPATH=/wpt-sync
    command: wptsync listen
    depends_on:
      - celery
  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
  celery:
    user: wptsync
    build: .
    volumes:
     - .:/home/wptsync/wpt-sync
    command: ./run_sync_tasks.sh --worker
    depends_on:
      - rabbitmq
